org.gradle.daemon=false
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.defaultConfig.externalNativeBuild.cmake.arguments=-DANDROID_STL=c++_shared
android.defaultConfig.externalNativeBuild.cmake.cppFlags=-fexceptions -frtti
android.defaultConfig.externalNativeBuild.cmake.cFlags=-Wl,--no-static
android.defaultConfig.externalNativeBuild.cmake.cppFlags=-Wl,--no-static
kotlin.daemon.jvm.options=-Xmx2048m

# Toolchain configuration
org.gradle.jvm.toolchain.install.fromMaven=false
org.gradle.jvm.toolchain.download=false
